pipeline {
    agent { label 'host' }
    stages {
        stage('Build') {
            steps {
                sh 'chmod 700 -R scripts/'
                sh './scripts/docker-build.sh prod'
            }
        }
        stage('OWASP DependencyCheck') {
            agent { label 'host' }
            steps {
                dependencyCheck additionalArguments: '--format HTML --format XML', odcInstallation: 'OWASP Dependency Check'
            }
        }
        stage('Deploy and Test') {
            steps {
                sh 'chmod 700 -R scripts/'
                sh './scripts/docker-deploy.sh prod'
                sh './scripts/test.sh prod'
            }
        }
    }
    post {
        success {
            node('host') {
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
            }
        }
    }
}
