version: '3.3'
services:
    nginx-waf:
        image: custom-nginx-waf
        container_name: ${NGINX_HOST}
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        volumes:
             - ./nginx-waf/data/nginx/templates/:/etc/nginx/templates/
             - ${SSL_CERT_PATH}:/etc/nginx/ssl:ro
        environment:
            - PROXY=1
            - MODSEC_AUDIT_ENGINE=On
            - MODSEC_RULE_ENGINE=On
            - ANOMALY_INBOUND=10
            - HEALTH=${HEALTH}
        restart: always
        privileged: true
        build: ./nginx-waf/
