version: '3.3'
services:
    nginx-waf:
        build: ./nginx-waf/
        networks:
            - waf-to-frontend
        ports:
            - '${HTTP_PORT}'
            - '${HTTPS_PORT}'
        volumes:
            - ./nginx-waf/data/nginx/templates/:/etc/nginx/templates/:ro
            - ${LOCAL_SSL_CERT_PATH}:/etc/letsencrypt/live/3x03.redapplepie.com/fullchain.pem:ro
            - ${LOCAL_SSL_KEY_PATH}:/etc/letsencrypt/live/3x03.redapplepie.com/privkey.pem:ro
        environment:
            - PROXY=1
            - MODSEC_AUDIT_ENGINE=On
            - MODSEC_RULE_ENGINE=On
            - ANOMALY_INBOUND=10
            - HEALTH=${HEALTH}
        restart: always
        privileged: true

    frontend:
        build: ./cinema-booking/frontend
        networks:
            - waf-to-frontend
            - frontend-to-identity
            - frontend-to-booking
            - frontend-to-movie
        ports:
            - "${FRONTEND_PORT}"

    # ports for services exposed to test the containers
    # will remove ports once we implement the APIs
    identity:
        build: 
            context: ./cinema-booking
            dockerfile: ./identity/Dockerfile
        networks:
            - frontend-to-identity
            - identity-to-payment
            - identity-to-databaseservice
        environment:
            PYTHONUNBUFFERED: 1
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        ports:
            - "${IDENTITY_PORT}"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "20"

    movie:
        build: 
            context: ./cinema-booking
            dockerfile: ./movie/Dockerfile
        networks:
            - frontend-to-movie
            - movie-to-databaseservice
        environment:
            PYTHONUNBUFFERED: 1
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        ports:
            - "${MOVIE_PORT}"
    
    booking:
        build: 
            context: ./cinema-booking
            dockerfile: ./booking/Dockerfile
        networks:
            - frontend-to-booking
            - booking-to-payment
            - booking-to-databaseservice
        environment:
            PYTHONUNBUFFERED: 1
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        ports:
            - "${BOOKING_PORT}"

    payment:
        build: 
            context: ./cinema-booking
            dockerfile: ./payment/Dockerfile
        networks:
            - identity-to-payment
            - booking-to-payment
            - payment-to-databaseservice
        environment:
            PYTHONUNBUFFERED: 1
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        ports:
            - "${PAYMENT_PORT}"

    databaseservice:
        build: 
            context: ./cinema-booking
            dockerfile: ./databaseservice/Dockerfile
        networks:
            - identity-to-databaseservice
            - movie-to-databaseservice
            - payment-to-databaseservice
            - booking-to-databaseservice
            - databaseservice-to-database
        environment:
            PYTHONUNBUFFERED: 1
            DB_HOST: database
            DB_NAME: ${DBSVC_NAME}
            DB_NORMALUSER: ${DBSVC_NORMALUSER}
            DB_NORMALPASSWORD: ${DBSVC_NORMALPASSWORD}
        ports:
            - "${DBSERVICE_PORT}"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "20"
        depends_on:
            - database

    database:
        build: ./cinema-booking/database
        networks:
            - databaseservice-to-database
        environment:
            POSTGRES_DB: ${SUPERUSER_DB_NAME}
            POSTGRES_USER: ${POSTGRES_SUPERUSER}
            POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_NORMALUSER: ${DB_NORMALUSER}
            DB_NORMALPASSWORD: ${DB_NORMALPASSWORD}
        volumes:
            - ./cinema-booking/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
            - postgres_container:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}"

networks:
  waf-to-frontend:
    driver: bridge
  frontend-to-identity:
    driver: bridge
  frontend-to-booking:
    driver: bridge  
  frontend-to-movie:
    driver: bridge
  booking-to-payment:
    driver: bridge
  identity-to-payment:
    driver: bridge  
  identity-to-databaseservice:
    driver: bridge
  movie-to-databaseservice:
    driver: bridge
  payment-to-databaseservice:
    driver: bridge
  booking-to-databaseservice:
    driver: bridge
  databaseservice-to-database:
    driver: bridge   

volumes:
  postgres_container:
