version: '3.3'
services:
  ubuntu:
      image: ubuntu
      networks:
          - waf-to-frontend
          - frontend-to-identity
          - frontend-to-booking
          - booking-to-payment
          - frontend-to-movie
          - databaseservice-to-database
      command: bash -c 'echo test'

networks:
  waf-to-frontend:
    name: cinema-${ENV}_waf-to-frontend
    external: true
  frontend-to-identity:
    name: cinema-${ENV}_frontend-to-identity
    external: true
  frontend-to-booking:
    name: cinema-${ENV}_frontend-to-booking
    external: true 
  frontend-to-movie:
    name: cinema-${ENV}_frontend-to-movie
    external: true
  booking-to-payment:
    name: cinema-${ENV}_booking-to-payment
    external: true
  identity-to-payment:
    name: cinema-${ENV}_identity-to-payment
    external: true
  identity-to-databaseservice:
    name: cinema-${ENV}_identity-to-databaseservice
    external: true
  movie-to-databaseservice:
    name: cinema-${ENV}_movie-to-databaseservice
    external: true
  payment-to-databaseservice:
    name: cinema-${ENV}_payment-to-databaseservice
    external: true
  booking-to-databaseservice:
    name: cinema-${ENV}_booking-to-databaseservice
    external: true
  databaseservice-to-database:
    name: cinema-${ENV}_databaseservice-to-database
    external: true
