# Use the official PostgreSQL image as the base image
FROM postgres:latest


# Set the environment variable for the PostgreSQL password
ENV POSTGRES_PASSWORD=mysecretpassword

# Expose the default PostgreSQL port
EXPOSE 5432
