version: '3'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - front-to-back
    ports:
      - "8080:8080"

# ports for services exposed to test the containers
# will remove ports once we implement the APIs
  identity:
    container_name: identity
    build: ./identity
    networks:
      - front-to-back
    ports:
      - "8081:8081"

  movie:
    container_name: movie
    build: ./movie
    networks:
      - front-to-back
    ports:
      - "8082:8082"
  
  booking:
    container_name: booking
    build: ./booking
    networks:
      - front-to-back
    ports:
      - "8083:8083"

  payment:
    container_name: payment
    build: ./payment
    networks:
      - front-to-back
    ports:
      - "8084:8084"

  databaseservice:
    container_name: databaseservice
    build: ./databaseservice
    networks:
      - front-to-back
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8085:8085"

  database:
    container_name: database
    build:
      context: ./database
    networks:
      - front-to-back  
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_container:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  front-to-back:
    driver: bridge
volumes:
  postgres_container: