version: '3'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - frontend-to-identity
      - frontend-to-booking
      - frontend-to-movie
    ports:
      - "8080:8080"

# ports for services exposed to test the containers
# will remove ports once we implement the APIs
  identity:
    container_name: identity
    build: ./identity
    networks:
      - frontend-to-identity
      - identity-to-payment
      - identity-to-databaseservice
    ports:
      - "8081:8081"

  movie:
    container_name: movie
    build: ./movie
    networks:
      - frontend-to-movie
      - movie-to-databaseservice
    ports:
      - "8082:8082"
  
  booking:
    container_name: booking
    build: ./booking
    networks:
      - frontend-to-booking
      - booking-to-payment
      - booking-to-databaseservice
    ports:
      - "8083:8083"

  payment:
    container_name: payment
    build: ./payment
    networks:
      - identity-to-payment
      - booking-to-payment
      - payment-to-databaseservice
    ports:
      - "8084:8084"

  databaseservice:
    container_name: databaseservice
    build: ./databaseservice
    networks:
      - identity-to-databaseservice
      - movie-to-databaseservice
      - payment-to-databaseservice
      - booking-to-databaseservice
      - databaseservice-to-database
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8085:8085"

  database:
    container_name: database
    build:
      context: ./database
    networks:
      - databaseservice-to-database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_container:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  frontend-to-identity:
    driver: bridge
  frontend-to-booking:
    driver: bridge  
  frontend-to-movie:
    driver: bridge
  booking-to-payment:
    driver: bridge
  identity-to-payment:
    driver: bridge  
  identity-to-databaseservice:
    driver: bridge
  movie-to-databaseservice:
    driver: bridge
  payment-to-databaseservice:
    driver: bridge
  booking-to-databaseservice:
    driver: bridge
  databaseservice-to-database:
    driver: bridge        

volumes:
  postgres_container: