pipeline {
    agent { label 'builtin' }
    stages {
        stage('Build') {
            steps {
                sh 'chmod 700 -R scripts/'
                sh './scripts/test-build.sh'
            }
        }
        stage('OWASP DependencyCheck') {
            steps {
                dependencyCheck additionalArguments: '--format HTML --format XML', odcInstallation: 'OWASP Dependency Check'
            }
        }
        stage('Test') {
            steps {
                sh 'chmod 700 -R scripts/'
                sh './scripts/test-deploy.sh'
                sh 'docker ps'
                echo 'Add test step here'
                sh './scripts/unit-test.sh'
                sh './scripts/test-kill-volumes.sh'
            }
        }
    }
    post {
        success {
            dependencyCheckPublisher pattern: 'dependency-check-report.xml'
        }
    }
}