pipeline {
    agent { label 'builtin' }
    stages {
        stage('Build') {
            steps {
                sh 'chmod 700 -R scripts/'
                sh './scripts/docker-build.sh test'
            }
        }
        stage('OWASP DependencyCheck') {
            steps {
                dependencyCheck additionalArguments: '--format HTML --format XML', odcInstallation: 'OWASP Dependency Check'
            }
        }
        stage('Test') {
            steps {
                sh 'chmod 700 -R scripts/'
                sh './scripts/docker-deploy.sh test'
                sh 'docker ps'
                echo 'Add test step here'
                sh './scripts/test.sh test'
                sh './scripts/docker-kill-volumes.sh test'
            }
        }
    }
    post {
        success {
            dependencyCheckPublisher pattern: 'dependency-check-report.xml'
        }
    }
}