pipeline {
    agent any

    environment {
        FLASK_ENV = 'development'
    }

    stages {
        stage('Checkout') {
            steps {
                // Retrieve code from version control
                checkout scm
            }
        }

        stage('Setup Python') {
            steps {
                // Set up Python virtual environment and install dependencies
                script {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Unit Test') {
            steps {
                // Run unit tests for app.py and booking_utils.py
                script {
                    sh '''
                    . venv/bin/activate
                    python -m unittest test_app.py
                    python -m unittest test_booking_utils.py
                    '''
                }
            }
        }

    }

    post {
        always {
            // Clean up
            cleanWs()
        }
    }
}
