pipeline {
    agent { label 'host' }

    stages {
        stage('Build') {
            steps {
                sh 'chmod 700 -R scripts/'
                sh './scripts/stg-build.sh'
            }
        }
        stage('Test') {
            steps {
                sh './scripts/dev-deploy.sh'
                echo "Add test step here"
                snykSecurity(
                    snykInstallation: 'Snyk',
                    snykTokenId: 'd3c397ce-d278-4da3-9ec4-a8cb545c3921',
                    // place other parameters here
                )
                sh './scripts/dev-kill.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh './scripts/stg-deploy.sh'
            }
        }
    }
}
